repositories:
- name: bitnami
  # use a former version of index.yaml from the git repository as Bitnami all removed charts older than 6 months from
  # the index.yaml descriptor, see https://github.com/bitnami/charts/issues/10539
  url: https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
- name: elastic
  url: https://helm.elastic.co/
- name: nuxeo
  url: https://chartmuseum.platform.dev.nuxeo.com/

helmDefaults:
  timeout: 300
  wait: true

releases:
- name: mongodb
  chart: bitnami/mongodb
  version: 7.14.2
  namespace: {{ requiredEnv "NAMESPACE" }}
  condition: mongodb.enabled
  values:
  - values/values-mongodb.yaml.gotmpl
- name: elasticsearch
  chart: elastic/elasticsearch
  version: 7.17.3
  namespace: {{ requiredEnv "NAMESPACE" }}
  condition: elasticsearch.enabled
  values:
  - values/values-elasticsearch.yaml.gotmpl
  # Suppress some environment variables that can't be removed through values files that crash application startup
  strategicMergePatches:
  - apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: elasticsearch-master
    spec:
      template:
        spec:
          containers:
          - name: elasticsearch
            env:
            # The cluster.deprecation_indexing.enabled env var is set since ES 7.16 chart version, not working on our application version
            - name: cluster.deprecation_indexing.enabled
              $patch: delete
            # The node.ml env var is set since ES 7.12 chart version, and it is not available in the oss version
            - name: node.ml
              $patch: delete
- name: kafka
  chart: bitnami/kafka
  version: 14.9.3
  namespace: {{ requiredEnv "NAMESPACE" }}
  condition: kafka.enabled
  values:
  - values/values-kafka.yaml.gotmpl

environments:
  # Required when running helmfile commands without any environment to not fail during strategicMergePatches resolution.
  default:
    values:
    - labels:
        usage: "default"
  mongodbUnitTests:
    values:
    - environments/unit-tests-mongodb.yaml
